baseurl = "https://ols.io/"
languageCode = "en-us"
title = "ols.io"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
publishDir = "docs"

[params]
    site_author = "Oliver Schneider"
    # site_description = ""
    location = "Lausanne"
    # Link custom assets relative to /static
    avatar = "https://www.gravatar.com/avatar/3e176fcfc7fd1061ce69fec616eb1484"
    header_background = "images/cover.jpg"
    # header_title = ""
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    # google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "inbx"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "olsio"
    gplus     = ""
